### ISSUE TITLE
[1.11.2] Hand Render Issue

### ISSUE THREAD

**Issue by Keono** [CreativeMD/CMDCam#1] opened 2017-01-11 08:48 UTC
Hand isn't rendered, along with any held items in the hand.

**Comment by CreativeMD** [comment] 2017-01-12 12:42
I couldn't reproduce this issue, do you have any other mods installed? Maybe send a screenshot?

**Comment by Keono** [comment] 2017-01-12 21:24
My bad, should have done that in the first place. I am running it a long with a personal modpack. However I just ran it without mods. Current Forge Version .2201 (Beta, This may be the cause, will probably update soon when I get the chance, running Liteloader aswell) Alongside is the inability to hit objects. Noticed this a bit ago
![2017-01-12_16 16 18](https://cloud.githubusercontent.com/assets/24986200/21908714/e3bd7ae0-d8e2-11e6-99ed-f8dc6b5fe138.png)

**Comment by CreativeMD** [comment] 2017-01-13 17:18
Oh, i fixed it, my bad :D. Thanks for reporting, should be fixed in v1.1.4

**Closed as completed by CreativeMD** 2017-01-13 17:18 UTC
